export enum ContactErrorCodes {
  NOT_FOUND = 'ERR_CONTACT_NOT_FOUND',
  ALREADY_EXISTS = 'ERR_CONTACT_ALREADY_EXISTS',
  CSV_GENERATION_FAILED = 'ERR_CSV_GENERATION_FAILED',
  CSV_IMPORT_FAILED = 'ERR_CSV_IMPORT_FAILED',
}
