services:
  postgres:
    image: postgres:14.1
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./setup_db.sh:/docker-entrypoint-initdb.d/setup_db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    env_file:
      - env-example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

  maildev:
    build:
      context: .
      dockerfile: Dockerfile.maildev
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025