export enum UserErrorCodes {
  NOT_FOUND = 'ERR_USER_NOT_FOUND',
  ALREADY_EXISTS = 'ERR_USER_ALREADY_EXISTS',
  HASH_NOT_FOUND = 'ERR_USER_HASH_NOT_FOUND',
  INVALID_PROVIDER = 'ERR_INVALID_PROVIDER',
  UNVERIFIED_USER = 'ERR_UNVERIFIED_USER',
  INCORRECT_PASSWORD = 'ERR_INCORRECT_PASSWORD',
  MISSING_PASSWORD = 'ERR_MISSING_PASSWORD',
  FORBIDDEN_RESOURCE = 'ERR_FORBIDDEN_RESOURCE',
  UNAUTHORIZED = 'ERR_UNAUTHORIZED',
}
